#! /bin/sh
set -euf

strip=false
verbose=false

while test $# -gt 0; do
  case $1 in
    --strip|--verbose)
      eval "${1:2}=true"
      shift
      ;;
    -*)
      echo "unknown option: $1" >&2
      exit 23
      ;;
    *)
      break
      ;;
  esac
done

exe=$1
name=$(basename $exe)
appdir=${2-$name}

case $verbose in
  true)
    MKDIR='mkdir -v'
    CP='cp -v'
    CHMOD='chmod -v'
    STRIP='strip -v'
    ;;
  *)
    MKDIR=mkdir
    CP=cp
    CHMOD=chmod
    STRIP=strip
    ;;
esac

echo '#! /bin/sh
set -euf
main() {
  strip='$strip'
  mkapp '$appdir''

ldd $exe | sed -n '
  s/[[:space:]]\+/ /g
  s@^ \([^ ]\+\) => \(/[^ ]\+\) (.*)$@#1lib \2 \1@p
  s@^ \(/[^ ]\+\) (.*)$@#2loader \1@p
' | sort | sed 's/#[0-9]/  /'
echo '}
mkapp() {
  app=$1
  '"$MKDIR"' $app
  '"$CP"' '$exe' $app
  cd $app
}
lib() { '"$CP"' -L $1 $2; }
loader() {
  '"$CP"' -L $1 .
  case $strip in
    true)
      ls | xargs '"$CHMOD"' u+w
      ls | xargs '"$STRIP"' -p --strip-unneeded
  esac
  loader=$(basename $1)
  mkindex $loader > index
  '"$CHMOD"' +x index
  '"$CHMOD"' -R a-w .
  cd -
}
mkindex() {
  echo "#! /bin/sh"
  echo "set -euf"
  echo "app=\$(dirname \$0)"
  echo "echo \$app"
  echo "exec \$app/$1 --library-path \$app \$app/'$name' \"\$@\""
}
main "$@"'
